name: Test, Build, and Publish Packages

on:
  release:
    types: [published]
    tags:
      - 'v*'
  workflow_dispatch:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ohiouniversity'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        
  publish-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com/'

      - run: npm install

      - run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

